name: "Boilerplate Build"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          extensions: intl, json, mbstring, xdebug, xml
          php-version: "${{ matrix.php-versions }}"
          coverage: xdebug
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Setup MySQL
        uses: samin/mysql-action@v1.3
      with:
        mysql version: 5.7
        mysql password: test
        mysql user: test
        mysql database: boilerplate-test
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Validate composer.json and composer.lock"
        run: "composer validate"
      - name: "Install dependencies"
        run: "composer install --prefer-source --no-progress --no-suggest"
      - name: "Run test suite"
        run: "composer test"